#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# generated by LLM
"""
Markdown文件合并工具 - 专为知识库导入设计
将当前目录及子目录中的所有Markdown文件合并为单一文件
"""

import os
import argparse
from pathlib import Path
import logging
from typing import List, Set

# 配置日志
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler('merge_notes.log', encoding='utf-8')
    ]
)
logger = logging.getLogger(__name__)

class MarkdownMerger:
    def __init__(self, output_file: str = "merge_notes_for_rag.md", 
                 max_size_mb: float = 10.0, exclude_dirs: Set[str] = None,
                 exclude_files: Set[str] = None):
        """
        初始化合并器
        
        Args:
            output_file: 输出文件名
            max_size_mb: 最大文件大小限制(MB)
            exclude_dirs: 要排除的目录集合
            exclude_files: 要排除的文件集合
        """
        self.output_file = output_file
        self.max_size_bytes = int(max_size_mb * 1024 * 1024)
        
        # 默认跳过的目录
        default_skip_dirs = {
            'tools', '.vscode', '.git', 'node_modules', 'book', 
            '__pycache__', '.pytest_cache', 'dist', 'build'
        }
        self.exclude_dirs = default_skip_dirs.union(exclude_dirs or set())
        self.exclude_files = exclude_files or set()
        
        # 统计信息
        self.processed_files = 0
        self.skipped_files = 0
        self.total_size = 0
        self.error_files = []

    def should_skip_directory(self, dir_name: str) -> bool:
        """判断是否应该跳过目录"""
        return (dir_name.startswith('.') or 
                dir_name in self.exclude_dirs)

    def should_skip_file(self, file_path: Path) -> bool:
        """判断是否应该跳过文件"""
        if file_path.suffix.lower() != '.md':
            return True
        
        if file_path.name in self.exclude_files:
            return True
            
        # 跳过输出文件本身
        if file_path.name == self.output_file:
            return True
            
        return False

    def collect_markdown_files(self, root_path: Path) -> List[Path]:
        """收集所有需要处理的Markdown文件"""
        md_files = []
        
        for root, dirs, files in os.walk(root_path):
            # 过滤掉要跳过的目录
            dirs[:] = [d for d in dirs if not self.should_skip_directory(d)]
            
            for file in files:
                file_path = Path(root) / file
                if not self.should_skip_file(file_path):
                    md_files.append(file_path)
        
        # 按路径排序，确保输出顺序一致
        return sorted(md_files)

    def read_file_content(self, file_path: Path) -> str:
        """安全读取文件内容"""
        encodings = ['utf-8', 'utf-8-sig', 'gbk', 'gb2312']
        
        for encoding in encodings:
            try:
                with open(file_path, 'r', encoding=encoding) as f:
                    return f.read()
            except UnicodeDecodeError:
                continue
            except Exception as e:
                logger.error(f"读取文件 {file_path} 时发生错误: {e}")
                self.error_files.append(str(file_path))
                return ""
        
        logger.warning(f"无法解码文件 {file_path}，跳过处理")
        self.error_files.append(str(file_path))
        return ""

    def format_file_header(self, file_path: Path, relative_path: str) -> str:
        """格式化文件头部信息"""
        separator = "=" * 80
        return f"""
{separator}
文件路径: {relative_path}
文件名: {file_path.name}
{separator}

"""

    def merge_files(self, root_path: Path = None) -> bool:
        """合并所有Markdown文件"""
        if root_path is None:
            root_path = Path('.')
        
        logger.info(f"开始扫描目录: {root_path.absolute()}")
        md_files = self.collect_markdown_files(root_path)
        
        if not md_files:
            logger.warning("未找到任何Markdown文件")
            return False
        
        logger.info(f"找到 {len(md_files)} 个Markdown文件")
        
        try:
            with open(self.output_file, 'w', encoding='utf-8', newline='\n') as output:
                # 写入文件头
                output.write(f"""# 合并的Markdown笔记文件

> 本文件由 merge_notes_for_rag.py 自动生成
> 生成时间: {self._get_current_time()}
> 包含文件数量: {len(md_files)}

---

""")
                
                current_size = len(output.getvalue().encode('utf-8')) if hasattr(output, 'getvalue') else 0
                
                for i, file_path in enumerate(md_files, 1):
                    try:
                        # 显示进度
                        print(f"\r处理进度: {i}/{len(md_files)} ({i/len(md_files)*100:.1f}%)", end='', flush=True)
                        
                        # 读取文件内容
                        content = self.read_file_content(file_path)
                        if not content.strip():
                            self.skipped_files += 1
                            continue
                        
                        # 计算相对路径
                        try:
                            relative_path = file_path.relative_to(root_path)
                        except ValueError:
                            relative_path = file_path
                        
                        # 格式化输出内容
                        file_header = self.format_file_header(file_path, str(relative_path))
                        formatted_content = f"{file_header}{content}\n\n"
                        
                        # 检查文件大小限制
                        content_size = len(formatted_content.encode('utf-8'))
                        if current_size + content_size > self.max_size_bytes:
                            logger.warning(f"达到文件大小限制 ({self.max_size_bytes/1024/1024:.1f}MB)，停止添加文件")
                            break
                        
                        # 写入内容
                        output.write(formatted_content)
                        current_size += content_size
                        self.processed_files += 1
                        self.total_size += content_size
                        
                    except Exception as e:
                        logger.error(f"处理文件 {file_path} 时发生错误: {e}")
                        self.error_files.append(str(file_path))
                        self.skipped_files += 1
                        continue
                
                print()  # 换行
                
        except Exception as e:
            logger.error(f"写入输出文件时发生错误: {e}")
            return False
        
        return True

    def _get_current_time(self) -> str:
        """获取当前时间字符串"""
        from datetime import datetime
        return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    def print_statistics(self):
        """打印处理统计信息"""
        print("\n" + "="*60)
        print("处理统计信息:")
        print(f"成功处理文件数: {self.processed_files}")
        print(f"跳过文件数: {self.skipped_files}")
        print(f"错误文件数: {len(self.error_files)}")
        print(f"总文件大小: {self.total_size/1024/1024:.2f} MB")
        print(f"输出文件: {self.output_file}")
        
        if self.error_files:
            print("\n错误文件列表:")
            for error_file in self.error_files:
                print(f"  - {error_file}")
        
        print("="*60)

def main():
    parser = argparse.ArgumentParser(
        description="合并Markdown文件用于知识库导入",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
示例用法:
  python merge_notes_for_rag.py
  python merge_notes_for_rag.py -o my_notes.md
  python merge_notes_for_rag.py --max-size 5 --exclude-dir temp
  python merge_notes_for_rag.py --exclude-file README.md LICENSE.md
        """
    )
    
    parser.add_argument(
        '-o', '--output',
        default='merge_notes_for_rag.md',
        help='输出文件名 (默认: merge_notes_for_rag.md)'
    )
    
    parser.add_argument(
        '--max-size',
        type=float,
        default=200.0,
        help='最大文件大小限制(MB) (默认: 10.0)'
    )
    
    parser.add_argument(
        '--exclude-dir',
        action='append',
        help='要排除的目录 (可多次使用)'
    )
    
    parser.add_argument(
        '--exclude-file',
        action='append', 
        help='要排除的文件 (可多次使用)'
    )
    
    parser.add_argument(
        '--root-path',
        default='.',
        help='扫描的根目录路径 (默认: 当前目录)'
    )
    
    args = parser.parse_args()
    
    # 创建合并器实例
    merger = MarkdownMerger(
        output_file=args.output,
        max_size_mb=args.max_size,
        exclude_dirs=set(args.exclude_dir or []),
        exclude_files=set(args.exclude_file or [])
    )
    
    # 执行合并
    logger.info("开始合并Markdown文件...")
    success = merger.merge_files(Path(args.root_path))
    
    # 显示统计信息
    merger.print_statistics()
    
    if success:
        logger.info(f"合并完成！输出文件: {args.output}")
        print(f"\n✅ 合并成功！文件已保存为: {args.output}")
        print(f"📁 文件大小: {os.path.getsize(args.output)/1024/1024:.2f} MB")
        print("🚀 现在可以将此文件导入到知识库中")
    else:
        logger.error("合并过程中发生错误")
        print("\n❌ 合并失败，请检查日志文件 merge_notes.log")
        return 1
    
    return 0

if __name__ == "__main__":
    exit(main())